#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
$HOME/.config/polybar/launch.sh &
setxkbmap -rules evdev -model evdev -layout us -variant altgr-intl &
feh --bg-fill $HOME/.local/share/wallpapers/wallpaper.jpg &

killall "dunst"
dunst &

xsetroot -cursor_name left_ptr & 

bspc monitor -d '1' '2' '3' '4' '5' '6'
bspc config border_width         4
bspc config window_gap          15
bspc config top_padding         27

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"
bspc config presel_feedback_color "#6272a4"
