local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>f', builtin.find_files, {})
vim.keymap.set('n', '<leader>r', builtin.live_grep, {})
vim.keymap.set('n', '<leader>\\', builtin.buffers, {})
vim.keymap.set('n', '<leader>h', builtin.help_tags, {})
